version: '3.8'
services:
  db:
    image: mariadb:10.8
    restart: always
    network_mode: "host"
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: gtps_db
    volumes:
      - ./db_data:/var/lib/mysql

  gtps:
    build: .
    restart: always
    network_mode: "host"
    environment:
      DB_HOST: 127.0.0.1
      DB_USER: root
      DB_PASS: your_password
      DB_NAME: gtps_db

