services:
  db:
    image: mariadb:10.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: woigigawoi123
      MYSQL_DATABASE: gtps_db
      MYSQL_USER: gtps_admin
      MYSQL_PASSWORD: woigigawoi123
    command: ["mysqld", "--bind-address=0.0.0.0"]
    volumes:
      - ./db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pwoigigawoi123"]
      interval: 5s
      timeout: 5s
      retries: 5

  gtps:
    build: .
    restart: always
    ports:
      - "0.0.0.0:17091:17091/udp"
    environment:
      DB_HOST: db
      DB_USER: gtps_admin
      DB_PASS: woigigawoi123
      DB_NAME: gtps_db
      SERVER_IP: sanzgt.duckdns.org
      PUBLIC_IP: sanzgt.duckdns.org
    depends_on:
      db:
        condition: service_healthy